name: StatsPvP
version: 1.0.0
main: com.stats.StatsPlugin
api-version: 1.8
author: StatsDev
description: Stats, scoreboard e chat formatado para PvP 1.5.2 - Prime League

depend: [ArenaPvP]

commands:
  stats:
    description: Ver seus stats
    usage: /<command>
    permission: stats.use
    permission-message: Você não tem permissão para usar este comando!
  top:
    description: Ver top players
    usage: /<command> [kills|kdr]
    permission: stats.use
    permission-message: Você não tem permissão para usar este comando!

permissions:
  stats.use:
    description: Permite usar comandos de stats
    default: true

