name: ArenaPvP
version: 1.0.0
main: com.arena.ArenaPlugin
api-version: 1.8
author: ArenaDev
description: Auto-kit e spawn na arena para PvP 1.5.2

commands:
  arena:
    description: Teleporta para arena e dá kit
    usage: /<command>
    permission: arena.use
    permission-message: Você não tem permissão para usar este comando!

permissions:
  arena.use:
    description: Permite usar comando /arena
    default: true

