name: Delay
version: 1.0.0
main: com.delay.DelayPlugin
api-version: 1.8
author: DelayDev
description: Replica PvP da versão 1.5.2 para Paper 1.8.8

commands:
  delay:
    description: Comando principal do Delay
    usage: /<command> [help|ver|reset|reach|espada|knockback|bloqueio|critico|iframe|debug]
    permission: delay.admin
    permission-message: Você não tem permissão para usar este comando!

